version: 2
updates:
  # Maintain dependencies for JavaScript files (vulnerability checks)
  - package-ecosystem: npm
    directory: "/"  # Analyzes all JavaScript files in the root and subdirectories
    schedule:
      interval: weekly  # Adjust schedule as needed
    open-pull-requests-limit: 10
    commit-message:
      prefix: "security(deps)"  # Customize prefix for security-related updates
    reviewers:
      - "kiyarose"

  # Maintain dependencies for GitHub Actions (if applicable)
  - package-ecosystem: github-actions  # Keep if you use GitHub Actions workflows
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci(deps)"
    reviewers:
      - "kiyarose"
